---
- name: Garantir o dir do projeto
  ansible.builtin.file:
    path: /opt/app
    state: directory
    mode: '0755'

- name: Garantir o dir do site
  ansible.builtin.file:
    path: /opt/app/app
    state: directory
    mode: '0755'

- name: Copiado docker-compose.yml para o dir do projeto
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/app
    mode: '0644'

- name: Copiado o site para o dir do projeto
  ansible.builtin.copy:
    src: app/
    dest: /opt/app/app
    mode: '0644'

- name: Executado compose
  community.docker.docker_compose_v2:
    project_src: /opt/app
    state: present

- name: Helthcheck porta 8080
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 8080
    state: started
    timeout: 30
    delay: 2

- name: Healthcheck da aplicação HTTP
  ansible.builtin.uri:
    url: "http://127.0.0.1:8080"
    method: GET
    status_code: 200
    return_content: true
  register: _result
  until: _result.status == 200
  retries: 5
  delay: 3

