- name: Helthcheck porta 8080
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 8080
    state: started
    timeout: 30
    delay: 2

- name: Healthcheck da aplicação HTTP
  ansible.builtin.uri:
    url: "http://127.0.0.1:8080"
    method: GET
    status_code: 200
    return_content: true
  register: _result
  until: _result.status == 200
  retries: 5
  delay: 3